#!/bin/busybox sh

echo "plpkg (Progwilinux Packager) 26.5 | by progwi0"

if [ "$1" == "create-info" ]; then
    touch .PLPKG
elif [ "$1" == "pack" ]; then
    . ./.PLPKG
    zip -r ../${NAME}.plpkg .
    echo "Packed ${NAME} ${VERSION} (${ARCH})!"
elif [ "$1" == "unpack" ]; then
    unzip ${2}.plpkg -d /
    . /.PLPKG
    echo "Unpacked ${NAME} ${VERSION} (${ARCH})! Thanks for using plpkg."
    echo "Message from packer: ${AIM}"
    rm /.PLPKG
fi
